### ISSUE TITLE
Feature request: Advance to given RNG seed

### ISSUE THREAD

**Issue by Ownasaurus** [Savestate2A03/ssbm_rng_manip#1]
Would you be willing to output the steps needed to advance to a particular seed? I suppose it would be an additional option to choose from the main menu?

Thanks for your consideration.

**Comment by Ownasaurus** [comment]
I think this may have been resolved in  1ddb1cf. If so, this issue can be closed :)

**Comment by Savestate2A03** [comment]
yep, i totally just missed this somehow. closed!
